### ISSUE TITLE
Когда появятся новые картинки с медведями?

### ISSUE THREAD

**Issue by dezmound** [belodpav/shri-2018__homework_task_04#4]
В тестовом репозитории недостаток текстовых картинок в форме мишек

**Comment by belodpav** [comment]
@dezmound Скоро, очень скоро. В новой версии обязательно будут. :+1:

**Comment by belodpav** [comment]
Каких мишек хочешь видеть?

**Comment by dezmound** [comment]
@belodpav Оформи пачку белых медведей в хорошем качестве, плиз :bear:

**Comment by belodpav** [comment]
@dezmound  Заказ принят, в след. обновлениях ждем мишек :smile:
