### ISSUE TITLE
Сортировка содержимого папок

### ISSUE THREAD

**Issue by dezmound** [belodpav/shri-2018__homework_task_04#5]
Отсортируй в алфавитном порядке содержимое папок. Так будет более UF :unamused:

**Comment by belodpav** [comment]
@dezmound  Они, отсортированы в алфавитном порядке :cat:  Может есть предложения как что-нибудь улучшить с отображением содержимого папок?

**Comment by dezmound** [comment]
Я имел в виду чтобы сначала папки в алфавитно, а за ними файлы. :whale: :dash:

**Comment by dezmound** [comment]
@belodpav Сначала папки, а потом файлы. :whale: :dash:
